server:
  host: 0.0.0.0
  port: 7777
  ssl_keyfile: "private_key.pem"
  ssl_certfile: "certificate.pem"
rcon:
  port: 27016
  password: "yourrconpassword"
  host: "127.0.0.1"
auth:
  username: "admin"
  password: "admin"
  secret: "123456"
pz:
  server_name: servertest
  server_path: "D:\\Server"
  pz_exe_path: "D:\\PZ_Server"
  log_filename: "console.txt"
  password: "YourPasswdXYZ"
steam:
  apikey: "yourapisteamkey"
  steamcmd_path: "steamcmd_dir"
  cache_folder: "mod_cache"
  appid: 108600
discord:
  apikey: "yourdiscordkey"
  channel: 1234567890 # number only ! no ""
  enable: False
