server:
    port: 7777
rcon:
    port: 27015
    password: "TheBestPassword"
    host: "127.0.0.1"
auth :
    username : admin
    password : admin
    secret : "123456"
pz:
    path : "/Users/benjaminmarchand/IdeaProjects/project-zomboid-server-docker/workshop-mods/content/108600"
